# Generated by Django 4.0.4 on 2022-05-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=60)),
                ('resenha', models.TextField()),
                ('finalizado', models.BooleanField()),
            ],
        ),
    ]
