# Generated by Django 4.0.4 on 2022-05-27 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefas_finalizado_alter_tarefas_resenha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='finalizado',
            new_name='final',
        ),
    ]
