# Generated by Django 4.0.4 on 2022-05-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_rename_finalizado_tarefas_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='categoria',
            field=models.CharField(choices=[('L', 'Livre'), ('B', 'Livro'), ('F', 'Filme')], default='L', max_length=6),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='final',
            field=models.BooleanField(default=False, verbose_name='Finalizada'),
        ),
    ]
