# Generated by Django 4.0.4 on 2022-05-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_tarefas_categoria_alter_tarefas_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditarTarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(blank=True, max_length=60)),
                ('resenha', models.TextField(blank=True, max_length=300)),
                ('final', models.BooleanField(blank=True, default=False, verbose_name='Finalizada')),
                ('categoria', models.CharField(choices=[('L', 'Livre'), ('B', 'Livro'), ('F', 'Filme')], default='L', max_length=6)),
            ],
        ),
    ]
