# Generated by Django 4.0.4 on 2022-05-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_alter_editartarefas_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditarTarefas',
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='categoria',
            field=models.CharField(blank=True, choices=[('L', 'Livre'), ('B', 'Livro'), ('F', 'Filme')], default='L', max_length=6),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='final',
            field=models.BooleanField(blank=True, default=False, verbose_name='Finalizada'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='resenha',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='tarefa',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
