# Generated by Django 4.0.4 on 2022-05-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_delete_editartarefas_alter_tarefas_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='categoria',
            field=models.CharField(choices=[('L', 'Livre'), ('B', 'Livro'), ('F', 'Filme')], default='L', max_length=6),
        ),
    ]
